travis:
  secure:
    BINSTAR_TOKEN: azJjQJJ3AwRWcueVlo7EyYPB5ls04Vx8IkYVIfLoRc84NJ1aePU2B15gBaHROPx9jrDHcVzfWLKaq+qj19C1kMUViIgxeMJ/+2kst8d2TrPoVy9fiHRWUnim/MNluUhBfnXxyeLxnWbJX4pBJBOpAiU1wi+WO/d88EWxfx2aPhQfiEXuD+j66mGYmOVrZ2mwPDVKFOp+8r9bmT9OE162HKJEepVcWiNi+wR58rp91wV3rA18Ouwzw1AmuQb88l3bdKjN8h2pAbIKOopDTv4pU89hLd3HqPkyAuTF67dSQzliMhZBjpl9C0468GH+rs7/EUUqoZIVMNRpZ4j6clqwDf/GB49bUnUZlbLavkqkbyK4NdLIX2zu9iWWQkpXVj0VZDCyFBsRqjOcElM6nO7NhRfBMVrdUgzVFLID24G58u/qMKORpX6d17t5e9baNRBDhe/3cRokB1et681g8iFKRmVdhJ+wCvbMx6KjEVP6csAV46713PoNGv9GUx4utJyLx/ttlxrGLMFcix6mpZV3kBRfk2prySzuZ3DvVqIRpujiPK+3XvIUPXIfxmsFmf9nxPJ05GQ4FcLBC81wKmbd+icCrPVwGZyUaHqGfNaBM06av/6FcAa+8muMiz8CnLJb3d7rknJKrexXTAYdCPH7mHLHDFUqE6+gfSY222jP1zs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
